# need 4 gpus

project: coconut
save_path: /home/jivitesj/projects/safety-1/coconut/lndata/checkpoints/llama32_3b/stage1/
name: gsm-coconut-llama32_3b

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 2
epochs_per_stage: 3
max_latent_stage: 3
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: meta-llama/Llama-3.2-3B
load_model_path: /home/jivitesj/projects/safety-1/coconut/lndata/checkpoints/llama32_3b/stage0/gsm-cot-llama32_3b/checkpoint_7
seed: 0
resume: 3
bf16: True
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: True
batch_size_training: 32
debug: False
gradient_accumulation_steps: 1
num_epochs: 25
lr: !!float "1e-4"
weight_decay: 0.01