# need 4 gpus

project: coconut
save_path: /home/jivitesj/projects/safety-1/coconut/lndata/checkpoints/qwen3_4b/stage1/
name: gsm-coconut-qwen3_4b

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 2
epochs_per_stage: 3
max_latent_stage: 3
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: Qwen/Qwen3-4B-Base
load_model_path: /home/jivitesj/projects/safety-1/coconut/lndata/checkpoints/qwen3_4b/stage0/gsm-cot-qwen3_4b/checkpoint_6
seed: 0
resume: 3
bf16: True
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: True
batch_size_training: 32
debug: False
gradient_accumulation_steps: 1
num_epochs: 25
lr: !!float "1e-5"
weight_decay: 0.01