# need 4 gpus

project: coconut
save_path: /home/jivitesj/projects/safety-1/coconut/lndata/checkpoints/prosqa/llama32_3b/
name: prosqa-coconut-llama32_3b

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 1
epochs_per_stage: 5
max_latent_stage: 6
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: meta-llama/Llama-3.2-3B
load_model_path: None
seed: 0
resume: 0
bf16: True
train_path: data/prosqa_train.json
val_path: data/prosqa_valid.json
reset_optimizer: True
batch_size_training: 8
debug: False
gradient_accumulation_steps: 4
num_epochs: 50
lr: !!float "1e-4"
weight_decay: 0.01